" Disable compatibility mode
set nocompatible

" Load plugins with Pathogen
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

" Enable syntax highlight
syntax on

filetype plugin indent on
